### ISSUE TITLE
All roles assigned to sysadmin

### ISSUE THREAD

**Issue by EloiSanchez** [EloiSanchez/snowflake-health-check#12]
### Description

Check for roles that have been not assigned to the SYSADMIN role. Best practices indicate that all custom roles created in Snowflake should be assigned to the SYSADMIN.

### Results

A table showing all the roles that are not assigned to the SYSADMIN role. The test should fail if it finds any.

**Comment by EloiSanchez** [comment]
Done in #2

**Comment by wiesnseb** [comment]
changes for streamlit
