### ISSUE TITLE
Accountadmin not posses any objects

### ISSUE THREAD

**Issue by wiesnseb** [EloiSanchez/snowflake-health-check#18]
### Description

The Accountadmin should not possess any objects, as these can only be modified by this extremely powerful role.

### Results

Pass if the account admin does not possess any objects.
Fail if the account admin does possess any objects, list of the objects as a result.

**Comment by wiesnseb** [comment]
changes for streamlit

**Comment by EloiSanchez** [comment]
Moved new requirements to new issue because we don't want them in milestone v0.1.0. Check #82.
