### ISSUE TITLE
Script to run all procedures

### ISSUE THREAD

**Issue by wiesnseb** [EloiSanchez/snowflake-health-check#58]
## Description
Write a script which runs all the procedures we need for the dashboards. All the result tables which are needed for the streamlit dashboard are generated by the procedures. A script or function should call all of them. 

### How to fix it
Best case would be to run the whole application just by running Home.py in the streamlit folder (not sure if feasible).
Also worth looking into how streamlit gets run in Snowflake so we don't need to change it again there

### Discussion is welcome
Yes

**Comment by EloiSanchez** [comment]
I would maybe not run everything when running Home.py. We have very lengthy health checks that would make the app super slow to start.

I would run the SLQ stuff on the Setup.sql script, which is run on installation on the app, and then have a button on the Home.py that the user could press to trigger all the checks again.

About how streamlit runs in Snowflake, it may be linked to #55 and #56.

**Comment by wiesnseb** [comment]
Maybe add a time estimation how long it takes to calculate (if somehow magically possible)

**Comment by EloiSanchez** [comment]
I think it would be nice to have a progress bar when running the procedures. I think `tqdm` module can be useful here.
