### ISSUE TITLE
queuing warehouses overview

### ISSUE THREAD

**Issue by DLampriadis** [EloiSanchez/snowflake-health-check#60]
### Description

A general plot showing an overview of all warehouses aggregating data for a predetermined time period. The time-period can be user determined or always give the aggregation for all time.

### Results

A table and a plot with the warehouse names and the total avg running, queuing and provisioning time that it experienced.

**Comment by EloiSanchez** [comment]
- [ ]  Should somehow be introduced in the Warehouse Overview page. I think that a new tab for it could be enough
- [ ] Maybe add a sort for most queuing / loaded warehosues

**Comment by EloiSanchez** [comment]
Moved to new issue so it is not included in the v0.1.0 milestone. Check #81
