### ISSUE TITLE
Check python procedures auto_suspend.py and stale_warehouses.py

### ISSUE THREAD

**Issue by wiesnseb** [EloiSanchez/snowflake-health-check#68]
## Description

- [x] File procedures/auto_suspend.py gives an error even tho its copied 1:1 from the sql file.
- [x] Double check procedures/utils.py. I get the broad sense behind the procedure create_tables_info() but need some more information to resolve this issue.
- [x] On top, not sure about the file procedures/stale_warehouses.py. The call query has a fixed number in it, are we still using this query at all or not?

### How to fix it
Refactor the code and split it. Make sure every class as a a create and call statement.

### I will fix this myself
No

**Comment by EloiSanchez** [comment]
Closed by #76
